package org.springdoclet.writers

import groovy.xml.MarkupBuilder

class HtmlWriter {
  void writeOutput(File outputFile, collectors, stylesheet) {
    def writer = new FileWriter(outputFile)
    def builder = new MarkupBuilder(writer)
    builder.html {
      head {
        title 'Spring Artifacts'
        link(rel:'stylesheet', type:'text/css', href:stylesheet)
      }
      body {
        h1 'Spring Artifacts'
        hr()
        for (collector in collectors) {
          collector.writeOutput builder 
          hr()
        }
        p('Generated by ') {
          a(href:'http://github.com/scottfrederick/springdoclet', 'SpringDoclet')
        }
      }
    }
  }
}
